name: OnePlus SM8750 Build SuKiSu SUSFS
on:
  workflow_dispatch:
    inputs:
      sukisu_version:
        description: "sukisu分支"
        required: true
        default: 'builtin'
      KERNEL_NAME:
        description: "修改内核名称"
        required: true
        default: '-android15-8-g013ec21bba94-abogki383916444'
      BUILD_TIME:
        type: string
        description: "自定义构建时间 (输入F使用当前时间)"
        required: false
        default: "Sun Jun 15 14:56:02 UTC 2025"
      BUILD_RUN:
        type: choice
        description: "RUN"
        required: true
        default: ubuntu-latest
        options:
          - ubuntu-latest
          - self-hosted
      enable_sched_ext:
       description: "是否添加风驰驱动"
       required: false
       default: true
       type: boolean
      enable_lto:
       description: "是否启用lto编译"
       required: false
       default: true
       type: boolean
      enable_Unicode_bypass_Fix:
       description: "零宽字符漏洞的修复补丁"
       required: false
       default: false
       type: boolean
      sukisu_tag:
        description: "自定义版本来源后缀"
        required: false
        default: "闲鱼-搞机英雄-禁止黑灰违法犯罪倒卖"
        

jobs:
  build:
    strategy:
      matrix:
        FEIL: ["oneplus_13", "oneplus_13_b", "oneplus_ace5_pro", "oneplus_ace5_pro_b","oneplus_13t", "oneplus_13t_b", "oneplus_pad_2_pro", "oneplus_pad_2_pro_b", "oneplus_ace5_ultra", "oneplus_ace6_w"]
            
    runs-on: ${{ github.event.inputs.BUILD_RUN }}
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
    steps:
      - name: Maximize build space
        if: ${{ github.event.inputs.BUILD_RUN == 'ubuntu-latest' }}
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          
      - name: Configure Git
        if: ${{ github.event.inputs.BUILD_RUN == 'ubuntu-latest' }}
        run: |
         git config --global user.name "build"
         git config --global user.email "123456@cnm.com"

      - name: Install dependencies
        if: ${{ github.event.inputs.BUILD_RUN == 'ubuntu-latest' }}
        run: |
         sudo apt update && sudo apt upgrade -y
         sudo apt install -y python3 git curl ccache libelf-dev aria2 dos2unix

      - name: Restore ccache
        if: ${{ github.event.inputs.BUILD_RUN == 'ubuntu-latest' }}
        uses: actions/cache@v3
        with:
          path: /home/runner/.ccache
          key: ${{ runner.os }}-${{ github.repository }}-${{ matrix.FEIL }}
          restore-keys: |
            ${{ runner.os }}-${{ github.repository }}-${{ matrix.FEIL }}-
            ${{ runner.os }}-
            ccache-
            
       # 4. 设置 ccache 环境变量  
      - name: Setup ccache environment
        if: ${{ github.event.inputs.BUILD_RUN == 'ubuntu-latest' }}
        run: |  
         echo "CCACHE_DIR=/home/runner/.ccache" >> $GITHUB_ENV  
         echo "CCACHE_MAXSIZE=8G" >> $GITHUB_ENV  
         echo "CCACHE_COMPILERCHECK=%compiler% -dumpmachine; %compiler% -dumpversion" >> $GITHUB_ENV  
         echo "CCACHE_NOHASHDIR=true" >> $GITHUB_ENV  
         echo "CCACHE_HARDLINK=true" >> $GITHUB_ENV  
         echo "CCACHE_BASEDIR=${{ github.workspace }}" >> $GITHUB_ENV  
         echo "CCACHE_LOGFILE=${{ github.workspace }}/ccache.log" >> $GITHUB_ENV  
         echo "/usr/lib/ccache" >> $GITHUB_PATH  
         
      - name: Show ccache stats
        run: |
         ccache -s || true

      - name: Install repo tool
        if: ${{ github.event.inputs.BUILD_RUN == 'ubuntu-latest' }}
        run: |
         curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
         chmod a+x ~/repo
         sudo mv ~/repo /usr/local/bin/repo

      - name: Initialize repo and sync
        run: |
         mkdir kernel_workspace && cd kernel_workspace
         repo init -u https://$TOKEN@github.com/JiuGeFaCai/sm8750.git -m ${{ matrix.FEIL }}.xml --depth=1
         repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
         rm kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports!"
         rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"
         if [ "${{ matrix.FEIL }}" = "oneplus_sm8750" ]; then
         cd kernel_platform/prebuilts/clang/host/linux-x86/
         mkdir zyc-clang
         cd zyc-clang
         wget https://github.com/ZyCromerZ/Clang/releases/download/19.0.0git-20240723-release/Clang-19.0.0git-20240723.tar.gz
         tar xf Clang-19.0.0git-20240723.tar.gz
         fi

      - name: Set up SukiSU
        run: |
         cd kernel_workspace/kernel_platform
         curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s ${{ github.event.inputs.sukisu_version }}
         cd KernelSU
         TAG_SUFFIX="${{ github.event.inputs.sukisu_tag }}"
         # 使用正确变量名 KSU_VERSION_API 替换函数体
         sed -i "s|\$(shell cd \$(KSU_SRC); \$(GIT_BIN) rev-parse --abbrev-ref HEAD)|$TAG_SUFFIX|g" kernel/Kbuild
         KSU_VERSION=$(expr $(/usr/bin/git rev-list --count main) "+" 37185)
         echo "KSUVER=${KSU_VERSION}_${{ matrix.FEIL }}" >> $GITHUB_ENV
         export KSU_VERSION=$KSU_VERSION
         echo "✅ Injected custom version: v$(KSU_VERSION)@$TAG_SUFFIX"
         
         
        
      - name: Set up susfs
        run: |
           cd kernel_workspace
           git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android15-6.6
           git clone https://github.com/SukiSU-Ultra/SukiSU_patch.git
           git clone https://$TOKEN@github.com/JiuGeFaCai/sturdy-journey.git

           cd kernel_platform        
           cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android15-6.6.patch ./common/
           cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/
           cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
           
           #lz4k
           if [ "${{ matrix.FEIL }}" != "oneplus_sm8750" ]; then
           cp -r ../SukiSU_patch/other/zram/lz4k/include/linux/* ./common/include/linux
           cp -r ../SukiSU_patch/other/zram/lz4k/lib/* ./common/lib
           cp -r ../SukiSU_patch/other/zram/lz4k/crypto/* ./common/crypto
           fi

           # Apply patches
           cp ../sturdy-journey/fix.patch ./common/
           cd ./common

           # Fake Patch to fix failures
           fake_patched=0
           if [ "${{ matrix.FEIL }}" = "oneplus_pad_2_pro" ] || [ "${{ matrix.FEIL }}" = "oneplus_ace5_ultra" ]; then
            if ! grep -qxF $'\tunsigned int nr_subpages = __PAGE_SIZE / PAGE_SIZE;' ./fs/proc/task_mmu.c; then
              echo "未找到 nr_subpages,正在进行补丁修复"
              sed -i -e '/int ret = 0, copied = 0;/a \\tunsigned int nr_subpages \= __PAGE_SIZE \/ PAGE_SIZE;' -e '/int ret = 0, copied = 0;/a \\tpagemap_entry_t \*res = NULL;' ./fs/proc/task_mmu.c
              fake_patched=1
            fi
           fi
           
           patch -p1 < 50_add_susfs_in_gki-android15-6.6.patch || true

           if [ "$fake_patched" = 1 ]; then
            if [ "${{ matrix.FEIL }}" = "oneplus_pad_2_pro" ] || [ "${{ matrix.FEIL }}" = "oneplus_ace5_ultra" ]; then
              if grep -qxF $'\tunsigned int nr_subpages = __PAGE_SIZE / PAGE_SIZE;' ./fs/proc/task_mmu.c; then
                sed -i -e '/unsigned int nr_subpages \= __PAGE_SIZE \/ PAGE_SIZE;/d' -e '/pagemap_entry_t \*res = NULL;/d' ./fs/proc/task_mmu.c
              fi
            fi
           fi

           cp ../../SukiSU_patch/hooks/syscall_hooks.patch ./
           #cp ../../SukiSU_patch/hooks/scope_min_manual_hooks_v1.6.patch ./

           if [ "${{ matrix.FEIL }}" = "oneplus_sm8750" ]; then
            sed -i '/#include <linux\/cpufreq_times.h>/a #ifdef CONFIG_KSU_SUSFS_SUS_MAP\n#include <linux/susfs_def.h>\n#endif' fs/proc/base.c
           fi

           #patch -p1 -F 3 < scope_min_manual_hooks_v1.6.patch
           
           echo "完成"

      - name: Apply lz4kd Patches
        run: |
          if [ "${{ matrix.FEIL }}" != "oneplus_sm8750" ]; then
          cd kernel_workspace/kernel_platform/common
          cp ../../SukiSU_patch/other/zram/zram_patch/6.6/lz4kd.patch ./
          patch -p1 -F 3 < lz4kd.patch || true
          fi

      - name: Apply Unicode bypass Fix
        if: ${{inputs.enable_Unicode_bypass_Fix }}
        run: |
         cd kernel_workspace/kernel_platform
         git clone https://$TOKEN@github.com/JiuGeFaCai/Unicode_bypass_Fix.git
         cp ./Unicode_bypass_Fix/unicode_bypass_fix_6.1+.patch ./common/
         cd ./common
         patch -p1 -F 3 < unicode_bypass_fix_6.1+.patch
           
      - name: Add SUSFS Configuration Settings
        run: |
          cd kernel_workspace/kernel_platform
          CONFIG_FILE=./common/arch/arm64/configs/gki_defconfig
          # SukiSU Ultra配置
          echo "CONFIG_KSU=y" >> "$CONFIG_FILE"

          # KPM配置
          echo "CONFIG_KPM=y" >> "$CONFIG_FILE"

          # # HOOK配置
          # if [ "${{ github.event.inputs.HOOK }}" = "kprobe" ]; then
          #   echo "CONFIG_KSU_SUSFS_SUS_SU=y" >> "$CONFIG_FILE"
          #   echo "CONFIG_KPROBES=y" >> "$CONFIG_FILE"
          #   echo "CONFIG_KSU_KPROBES_HOOK=y" >> "$CONFIG_FILE"
          # elif [ "${{ github.event.inputs.HOOK }}" = "manual" ]; then
          #   echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> "$CONFIG_FILE"
          #   echo "CONFIG_KSU_MANUAL_HOOK=y" >> "$CONFIG_FILE"
          # elif [ "${{ github.event.inputs.HOOK }}" = "tracepoint" ]; then
          #   echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> "$CONFIG_FILE"
          #   echo "CONFIG_KSU_TRACEPOINT_HOOK=y" >> "$CONFIG_FILE"
          # fi

          # SUSFS配置
          echo "CONFIG_KSU_SUSFS=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SUS_MAP=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> "$CONFIG_FILE"
          
          echo "CONFIG_CRYPTO_LZ4HC=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_CRYPTO_LZ4K=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_CRYPTO_LZ4KD=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_CRYPTO_842=y" >> ./common/arch/arm64/configs/gki_defconfig
         
          # Remove check_defconfig
          sed -i 's/check_defconfig//' ./common/build.config.gki
          cd common
          git add -A && git commit -a -m "BUILD Kernel"
          
      - name: Add make name
        run: |
          cd kernel_workspace/kernel_platform
          #sed -i '186s|echo ".*"|echo "${KERNELVERSION}${scm_version}${config_localversion}"|' common/scripts/setlocalversion
          #sed -i "s/\${scm_version}/${{ github.event.inputs.KERNEL_NAME }}/g" ./common/scripts/setlocalversion
          # 设置内核标识
          sed -i 's|\${config_localversion}\${LOCALVERSION}\${scm_version}|\${scm_version}\${config_localversion}\${LOCALVERSION}|' common/scripts/setlocalversion
          sed -i "s|\\\${scm_version}|${{ github.event.inputs.KERNEL_NAME }}|g" common/scripts/setlocalversion
         
      - name: Add sched_ext
        if: ${{inputs.enable_sched_ext }}
        run: |
         cd kernel_workspace/kernel_platform/common
         git clone https://github.com/JiuGeFaCai/SCHED_PATCH.git -b sm8750
          echo "正在拉取风驰补丁"
          cp ./SCHED_PATCH/fengchi_${{ matrix.FEIL }}.patch ./
          if [[ -f "fengchi_${{ matrix.FEIL }}.patch" ]]; then
            echo "正在打风驰补丁"
            dos2unix "fengchi_${{ matrix.FEIL }}.patch"
            patch -p1 -F 3 < "fengchi_${{ matrix.FEIL }}.patch"
            echo "fengchi_patch完成"
          else
            echo "❌ 未匹配到补丁，风驰内核暂未支持你的机型，请关闭后重试"
            exit 11
         fi

      - name: 拉取afdo
        run: |
          cd kernel_workspace/kernel_platform/
          git clone https://$TOKEN@github.com/JiuGeFaCai/afdo.git

      - name: use LTO=thin
        if: ${{inputs.enable_lto }}
        run: |
         cd kernel_workspace/kernel_platform
         echo "CONFIG_LTO_CLANG=y" >> ./common/arch/arm64/configs/gki_defconfig
         echo "CONFIG_LTO_CLANG_THIN=y" >> ./common/arch/arm64/configs/gki_defconfig

      # Custom kernel build time, without adding #1 SMP PREEMPT 自定义内核构建时间，不要加入#1 SMP PREEMPT
      - name: Custom BUILD_TIME
        shell: bash
        run: |
          INPUT_TIME="${{ github.event.inputs.BUILD_TIME }}"
          if [[ -n "$INPUT_TIME" && "$INPUT_TIME" != "F" && "$INPUT_TIME" != "f" ]]; then
            DATESTR="$INPUT_TIME"
            echo "Using input BUILD_TIME: $DATESTR"
          else
            DATESTR="$(TZ='UTC' date +'%a %b %d %T %Z %Y')"
            echo "Using UTC time as fallback: $DATESTR"
          fi
          echo "KBUILD_BUILD_TIMESTAMP=${DATESTR}" >> "$GITHUB_ENV"
          echo "KBUILD_BUILD_VERSION=1" >> "$GITHUB_ENV"
          cd kernel_workspace/kernel_platform/
          for f in common/scripts/mkcompile_h; do
            if [ -f "$f" ]; then
              echo "Patching mkcompile_h with BUILD_TIME=$DATESTR"
              if grep -q 'UTS_VERSION=' "$f"; then
                perl -pi -e "s{UTS_VERSION=\"\\\$\\(.*?\\)\"}{UTS_VERSION=\"#1 SMP PREEMPT $DATESTR\"}" "$f"
              else
                perl -0777 -pi -e "s{cat <<EOF}{cat <<EOF\n#undef UTS_VERSION\n#define UTS_VERSION \"#1 SMP PREEMPT $DATESTR\" } unless /UTS_VERSION/" "$f"
              fi
            fi
          done
      

      - name: Build kernel
        run: |

          if [ "${{ matrix.FEIL }}" != "oneplus_sm8750" ]; then
          export PATH="$GITHUB_WORKSPACE/kernel_workspace/kernel_platform/prebuilts/clang/host/linux-x86/clang-r510928/bin:$PATH"
          else
          export PATH="$GITHUB_WORKSPACE/kernel_workspace/kernel_platform/prebuilts/clang/host/linux-x86/zyc-clang/bin:$PATH"
          fi

          export PATH="/usr/lib/ccache:$PATH"
          
          # 设置 AFDO 配置文件路径
          export AFDO_PROFILE="${{ github.workspace }}/kernel_workspace/kernel_platform/afdo/kernel.afdo"
          if [ ! -f "$AFDO_PROFILE" ]; then
           echo "Error: AFDO profile not found at $AFDO_PROFILE"
          exit 1
          fi

          cd kernel_workspace/kernel_platform/common
          clang -v
          make -j$(nproc --all) LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC='ccache clang' RUSTC=../../prebuilts/rust/linux-x86/1.73.0b/bin/rustc PAHOLE=../../prebuilts/kernel-build-tools/linux-x86/bin/pahole LD=ld.lld  HOSTLD=ld.lld O=out KCFLAGS+="-Wno-error -fauto-profile=$AFDO_PROFILE" gki_defconfig all
          # 创建输出目录并复制 Image
          mkdir -p ../dist
          cp out/arch/arm64/boot/Image ../dist/

      # 6. 打印 ccache 使用统计
      - name: Show ccache stats
        run: ccache -s || true
         
      - name: Apply Linux Patch
        run: |
         cd kernel_workspace/kernel_platform/dist/
         curl -LSs "https://github.com/SukiSU-Ultra/SukiSU_KernelPatch_patch/releases/download/0.12.2/patch_linux" -o patch_linux
         chmod +x patch_linux
         ./patch_linux
         rm -f Image
         mv oImage Image
         
      - name: Make AnyKernel3
        run: |
         git clone https://github.com/WildPlusKernel/AnyKernel3.git --depth=1
         rm -rf ./AnyKernel3/.git
         rm -rf ./AnyKernel3/push.sh
         cp kernel_workspace/kernel_platform/dist/Image ./AnyKernel3/

      - name: Upload AnyKernel3
        uses: actions/upload-artifact@v4
        with:
         name: SuKiSu_${{ env.KSUVER }}
         path: ./AnyKernel3/*
         
      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
         name: Image_SuKiSu_${{ env.KSUVER }}
         path: kernel_workspace/kernel_platform/dist/Image
