name: OnePlus SM850 Build SuKiSu SUSFS
on:
  workflow_dispatch:
    inputs:
      ci_VERSION:
        description: "谷歌ci版本"
        required: true
        default: 'android16-6.12-2025-06'
      device_tag:
        description: "设备id"
        required: false
        default: "123456"
      KERNEL_NAME:
        type: string
        description: "自定义内核后缀 (留空则使用随机字符串)"
        required: false
        default: ""
      BUILD_TIME:
        type: string
        description: "自定义构建时间 (输入F使用当前时间)"
        required: false
        default: "Sun Jun 15 14:56:02 UTC 2025"
      sukisu_tag:
        description: "自定义版本来源后缀"
        required: false
        default: "闲鱼-搞机英雄-禁止黑灰违法犯罪倒卖"
      sukisu_version:
        description: "sukisu分支"
        required: true
        default: "susfs-main"
jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          
      - name: Configure Git
        run: |
         git config --global user.name "build"
         git config --global user.email "123456@qq.com"

      - name: Install dependencies
        run: |
         sudo apt update && sudo apt upgrade -y
         sudo apt install -y curl ccache git python3 repo libelf-dev
        
      - name: Install repo tool
        run: |
         curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
         chmod a+x ~/repo
         sudo mv ~/repo /usr/local/bin/repo

      - name: Initialize repo and sync
        run: |
         mkdir kernel_workspace && cd kernel_workspace
         export REPO_URL='https://mirrors.tuna.tsinghua.edu.cn/git/git-repo'
         repo init --depth=1 --u https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/kernel/manifest -b common-${{ github.event.inputs.ci_VERSION }} --repo-rev=v2.16
         REMOTE_BRANCH=$(git ls-remote https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/kernel/common ${{ github.event.inputs.ci_VERSION }})
         DEFAULT_MANIFEST_PATH=.repo/manifests/default.xml
         if grep -q deprecated <<< $REMOTE_BRANCH; then
         echo "Found deprecated branch: ${{ github.event.inputs.ci_VERSION }}"
         sed -i 's/"'${{ github.event.inputs.ci_VERSION }}'"/"deprecated\/'${{ github.event.inputs.ci_VERSION }}'"/g' $DEFAULT_MANIFEST_PATH
         cat $DEFAULT_MANIFEST_PATH
         fi
         repo --version
         repo --trace sync -c -j$(nproc --all) --no-tags
         rm -rf common
         git clone https://github.com/OnePlusOSS/android_kernel_common_oneplus_sm8850.git --depth 1 common

         
      - name: Set up SukiSU
        run: |
         cd kernel_workspace
         sed -i '/diff -u "${source_config}" ${OUT_DIR}\/defconfig >&2 || RES=$?/,/^[[:space:]]*fi$/d' build/kernel/_setup_env.sh
         curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s ${{ github.event.inputs.sukisu_version }}
         cd KernelSU
         TAG_SUFFIX="${{ github.event.inputs.sukisu_tag }}"
         # 使用正确变量名 KSU_VERSION_API 替换函数体
         sed -i "s|\$(shell cd \$(KSU_SRC); \$(GIT_BIN) rev-parse --abbrev-ref HEAD)|$TAG_SUFFIX|g" kernel/Makefile
         KSU_VERSION=$(expr $(/usr/bin/git rev-list --count main) "+" 37185)
         echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
         export KSU_VERSION=$KSU_VERSION
         echo "? Injected custom version: v$(KSU_VERSION)@$TAG_SUFFIX"
         
         
         
      - name: Set up susfs
        run: |
           cd kernel_workspace
           git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android16-6.12
           
           git clone https://github.com/ShirkNeko/SukiSU_patch.git
           cp susfs4ksu/kernel_patches/50_add_susfs_in_gki-android16-6.12.patch ./common/
           cp susfs4ksu/kernel_patches/fs/* ./common/fs/
           cp susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/

           # Apply patches
           cd ./common
           patch -p1 < 50_add_susfs_in_gki-android16-6.12.patch || true    
      
      # - name: Apply HOOK
      #   run: |
      #     cd kernel_workspace/common
      #     if [ "${{ github.event.inputs.HOOK }}" = "kprobe" ]; then
      #     echo "调用 kprobe 钩子"
      #     elif [ "${{ github.event.inputs.HOOK }}" = "manual" ]; then
      #     cp ../SukiSU_patch/hooks/scope_min_manual_hooks_v1.6.patch ./
      #     echo "调用 manual 钩子"
      #     patch -p1 -F 3 < scope_min_manual_hooks_v1.6.patch
      #     elif [ "${{ github.event.inputs.HOOK }}" = "tracepoint" ]; then
      #     cp ../SukiSU_patch/hooks/sukisu_tracepoint_hooks_v1.1.patch ./
      #     echo "调用 tracepoint 钩子"
      #     patch -p1 -F 3 < sukisu_tracepoint_hooks_v1.1.patch
      #     fi
      
      # Custom kernel build time, without adding #1 SMP PREEMPT 自定义内核构建时间，不要加入#1 SMP PREEMPT
      - name: Custom BUILD_TIME
        shell: bash
        run: |
          INPUT_TIME="${{ github.event.inputs.BUILD_TIME }}"
          if [[ -n "$INPUT_TIME" && "$INPUT_TIME" != *[Ff]* ]]; then
            DATESTR="$INPUT_TIME"
            echo "Using input BUILD_TIME: $DATESTR"
          else
            DATESTR="$(TZ='UTC' date +'%a %b %d %T %Z %Y')"
            echo "Using UTC time as fallback: $DATESTR"
          fi
          echo "KBUILD_BUILD_TIMESTAMP=${DATESTR}" >> "$GITHUB_ENV"
          echo "KBUILD_BUILD_VERSION=1" >> "$GITHUB_ENV"
          cd kernel_workspace/
          for f in common/scripts/mkcompile_h; do
            if [ -f "$f" ]; then
              echo "Patching mkcompile_h with BUILD_TIME=$DATESTR"
              if grep -q 'UTS_VERSION=' "$f"; then
                perl -pi -e "s{UTS_VERSION=\"\\\$\\(.*?\\)\"}{UTS_VERSION=\"#1 SMP PREEMPT $DATESTR\"}" "$f"
              else
                perl -0777 -pi -e "s{cat <<EOF}{cat <<EOF\n#undef UTS_VERSION\n#define UTS_VERSION \"#1 SMP PREEMPT $DATESTR\" } unless /UTS_VERSION/" "$f"
              fi
            fi
          done
          
      - name: oneplus
        run: |
         cd kernel_workspace
         git clone https://$TOKEN@github.com/JiuGeFaCai/sturdy-journey.git
         cp ./sturdy-journey/lsm.patch ./common/
         cd ./common
         patch -p1 -F 3 < lsm.patch

      # - name: sb
      #   run: |
      #    cd kernel_workspace/common/drivers
      #    git clone https://$TOKEN@github.com/JiuGeFaCai/device_check.git --depth 1
      #    TAG_DEVICE="${{ github.event.inputs.device_tag }}"
      #    sed -i "s/a2cbba3e/$TAG_DEVICE/g" device_check/serial_check.c
      #    echo "obj-y				+= device_check/" >> Makefile
         

      - name: Add SUSFS Configuration Settings
        run: |
          cd kernel_workspace
          CONFIG_FILE=./common/arch/arm64/configs/gki_defconfig
          # SukiSU Ultra配置
          echo "CONFIG_KSU=y" >> "$CONFIG_FILE"

          # KPM配置
          echo "CONFIG_KPM=y" >> "$CONFIG_FILE"

          # # HOOK配置
          # if [ "${{ github.event.inputs.HOOK }}" = "kprobe" ]; then
          #   echo "CONFIG_KSU_SUSFS_SUS_SU=y" >> "$CONFIG_FILE"
          #   echo "CONFIG_KPROBES=y" >> "$CONFIG_FILE"
          #   echo "CONFIG_KSU_KPROBES_HOOK=y" >> "$CONFIG_FILE"
          # elif [ "${{ github.event.inputs.HOOK }}" = "manual" ]; then
          #   echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> "$CONFIG_FILE"
          #   echo "CONFIG_KSU_MANUAL_HOOK=y" >> "$CONFIG_FILE"
          # elif [ "${{ github.event.inputs.HOOK }}" = "tracepoint" ]; then
          #   echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> "$CONFIG_FILE"
          #   echo "CONFIG_KSU_TRACEPOINT_HOOK=y" >> "$CONFIG_FILE"
          # fi

          # SUSFS配置
          echo "CONFIG_KSU_SUSFS=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SUS_MAP=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> "$CONFIG_FILE"
          
          # Remove check_defconfig
          sed -i 's/check_defconfig//' ./common/build.config.gki
          cd common
          if [ -f "BUILD.bazel" ]; then
          sed -i '/protected_module_names_list.*gki_aarch64_protected_module_names/d' BUILD.bazel
          fi
          git add -A && git commit -a -m "BUILD Kernel"

      - name: Add make name
        if: ${{ github.event.inputs.KERNEL_NAME != '' }}
        run: |
         cd kernel_workspace
         if [ "${{ github.event.inputs.KERNEL_VERSION }}" != "6.6" ]; then
         sed -i '$s|echo "\$res"|echo "\${{ github.event.inputs.KERNEL_NAME }}"|' ./common/scripts/setlocalversion
         else
         sed -i '$s|${file_localversion}|${{ github.event.inputs.KERNEL_NAME }}|' ./common/scripts/setlocalversion
         fi
   
      - name: Build kernel
        run: |
         cd kernel_workspace
         tools/bazel run --config=fast --config=stamp //common:kernel_aarch64_dist  -- --destdir=dist

      - name: Make AnyKernel3
        run: |
         OUTDIR=kernel_workspace/out/${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}/dist
         if [ ! -e $OUTDIR ]; then
           OUTDIR=kernel_workspace/dist
         fi
         mkdir output
         cp $OUTDIR/Image ./output/
         cd output
         curl -LSs "https://raw.githubusercontent.com/ShirkNeko/SukiSU_patch/refs/heads/main/kpm/patch_linux" -o patch_linux
         chmod +x patch_linux
         ./patch_linux
         rm -f Image
         mv oImage Image
         cd ..
         git clone https://github.com/WildPlusKernel/AnyKernel3.git --depth=1
         rm -rf ./AnyKernel3/.git
         cp ./output/Image ./AnyKernel3/

      - name: Upload AnyKernel3
        uses: actions/upload-artifact@v4
        with:
         name: SuKiSu_${{ env.KSUVER }}_android16-6-12
         path: ./AnyKernel3/*
         
      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
         name: Image
         path: ./output/*
